[project]
name = "pedaldrivenprogramming"
version = "3.0.0"
dependencies = [
    "Django",
    "dj-database-url",
    "psycopg",
    "whitenoise[brotli]",
]

[project.optional-dependencies]
dev = [
    "django-stubs",
    "pip-tools",
    "ruff"
]

[tool.setuptools]
py-modules = []
