# Generated by Django 5.0.2 on 2024-02-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdpImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('thumb', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('private', models.BooleanField(blank=True, default=True)),
                ('hidden', models.BooleanField(blank=True, default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
