# Generated by Django 5.0.2 on 2024-02-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdpimage',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='pdpimage',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='images/thumb/'),
        ),
    ]
